services:
 mongo-band:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_band_data:/data/db
    
 mysql-album:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_album_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-user:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 band-service:
  depends_on:
    - mongo-bands
  image: maartenwilloque/band-service
  ports:
    - 8080:8080
  links:
    - mongo-bands
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-bands
   
 user-service:
  depends_on:
    - mysql-user
  image: maartenwilloque/user-service
  ports:
    - 8082:8082
  links:
    - mysql-user
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3307

 album-service:
  depends_on:
    - band-service
    - user-service
  image: maartenwilloque/album-service
  ports:
    - 8081:8081
  links:
    - band-service
    - user-service
  environment:
   BAND_SERVICE_BASEURL: band-service:8080
   USER_INFO_SERVICE_BASEURL: user-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-album
   MYSQL_DB_PORT: 3306

volumes:
 mongodb_band_data:
 mysql_user_data:
 mysql_album_data: