server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: album
          uri: http://${ALBUM_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/album/{Id}
            - Method=GET
          filters:
            - SetPath=/api/album/{Id}
        - id: albums
          uri: http://${ALBUM_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - SetPath=/api/albums
        - id: band
          uri: http://${ALBUM_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/band/{Id}
            - Method=GET
          filters:
            - SetPath=/api/band/{Id}
        - id: rating
          uri: http://${USER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rating/{albumId}
            - Method=GET
          filters:
            - SetPath=/api/rating/average/{albumId}
        - id: post-rating
          uri: http://${USER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rating
            - Method=POST
          filters:
            - SetPath=/api/rating
        - id: get-ratings-user
          uri: http://${USER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ratings/{Id}
            - Method=GET
          filters:
            - SetPath=/api/rating/user/{Id}
        - id: delete-rating
          uri: http://${USER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rating/{Id}
            - Method=DELETE
          filters:
            - SetPath=/api/rating/{Id}

